% clear 
% close all
% clc

set_main_paths('salinity_glider');
InstrumentID = import_instrument_ids;


choice = {'PHASE 1. Load Data', ...
          'PHASE 2. Run Whitespace Maximization', ...
          'PHASE 3. Apply Correction Results', ...
          'PHASE 4. Export Metadata Files', ...
          'PHASE 5. Write L1_corr Data Files'};
      
choiceFunction = {'[GliderNcFilesList, GliderDataFile, CtdCorrDataFile, Campaign, TESTdat, global_meta, CTD, buttonMC, depNUM_glider] = phase_1_load_data( InstrumentID )', ...
    '[ GUESS, AXISlims ] = phase_2_run_whitespace( Campaign, CTD, buttonMC, TESTdat, CtdCorrDataFile, depNUM_glider )', ...
    '[ TESTdat ] = phase_3_apply_corrections( GUESS, TESTdat, depNUM_glider, CtdCorrDataFile )', ...
    '[ TESTdat, fnameOutPath ] = phase_4_export_metadata_files(TESTdat, CtdCorrDataFile, GliderDataFile, Campaign, AXISlims)', ...
    'write_L1_corr_data_files(fnameOutPath)'
    };
         
d = dialog('Position',[80 250 550 400],'Name','Glider Salinity Correction Pack');       
firstButtonY = 355;
firstButtonWidth = 350;
firstButtonX = 10;
firstBttonHeight = 40;
% txt = uicontrol('Parent',d,...
%        'Style','text',...
%        'Position',[20 80 210 40],...
%        'String','Select a color');
[x,~]=imread('LogoSocib.png');
I2=imresize(x, [102 113]);
socibLogo=uicontrol('Parent',d,...
            'units','pixels',...
            'position',[10 20 113 102],...
            'cdata',I2);
        
[x,~]=imread('gliderSocib.jpg');
I2=imresize(x, [202 140]);
ctdLogo=uicontrol('Parent',d,...
            'units','pixels',...
            'position',[380 162 140 202],...
            'cdata',I2);
        
[x,~]=imread('jericoLogo.jpg');
I2=imresize(x, [102 183]);
jericoLogo=uicontrol('Parent',d,...
            'units','pixels',...
            'position',[150 20 183 102],...
            'cdata',I2);


[~,n] = size(choice);
count = 0;
for i = 1:n
    stage(i) = uicontrol('Parent',d,...
       'Position',[firstButtonX firstButtonY - count firstButtonWidth firstBttonHeight],...
       'String',choice(i),...
       'fontSize',12, ...
       'Callback',choiceFunction{i}, ...
       'Interruptible', 'on');
    count = count + 45;
end



   
   
   
   
   
   